blank_issues_enabled: false
contact_links:
  - name: Question about the Twitter API? Ask in the Twitter Developer Community
    url: https://twittercommunity.com/
    about: For general API functionality questions, please ask in the developer forums.
